Repository Gamegoo-repo/Gamegoo-Server-v2, pull requests merged in 2025-08, with the labels that each got.

#403 [Feat/402] 테스트 편의성 API 구현
  src/main/java/com/gamegoo/gamegoo_v2/HomeController.java
  src/main/java/com/gamegoo/gamegoo_v2/account/member/service/MemberService.java
  src/main/java/com/gamegoo/gamegoo_v2/core/config/SecurityConfig.java
  src/main/java/com/gamegoo/gamegoo_v2/external/riot/controller/RiotController.java
  src/main/java/com/gamegoo/gamegoo_v2/external/riot/dto/request/RiotJoinRequest.java
  src/main/java/com/gamegoo/gamegoo_v2/external/riot/service/RiotFacadeService.java
Labels: :sparkles: feature

#401 [Ci/399] QA 전용 서버 배포 설정
  .github/workflows/deploy-qa.yml
  Dockerfile-qa
  src/main/java/com/gamegoo/gamegoo_v2/core/config/CorsProperties.java
  src/main/java/com/gamegoo/gamegoo_v2/core/config/SecurityConfig.java
  src/main/resources/application.yml
  src/main/resources/logback-spring.xml
  src/test/resources/application.yml
Labels: :construction_worker: cicd

#408 [Fix/407] 이메일 발송 계정 재설정
  src/main/resources/application.yml
  src/test/resources/application.yml
Labels: :bug: bug

#411 [Fix/400] 로그인 시 탈퇴 로직 추가
  src/main/java/com/gamegoo/gamegoo_v2/external/riot/service/RiotFacadeService.java
  src/main/java/com/gamegoo/gamegoo_v2/matching/service/MatchingFacadeService.java
  src/test/java/com/gamegoo/gamegoo_v2/integration/matching/MatchingFacadeServiceTest.java
Labels: :sparkles: feature

#417 [Feat/414] 친구 요청 수락 시 socket 서버 API 호출
  src/main/java/com/gamegoo/gamegoo_v2/external/socket/SocketService.java
  src/main/java/com/gamegoo/gamegoo_v2/social/friend/service/FriendFacadeService.java
  src/test/java/com/gamegoo/gamegoo_v2/integration/friend/FriendRequestFacadeServiceTest.java
Labels: :sparkles: feature
