Repository Gamegoo-repo/Gamegoo-Server-v2, pull requests merged in 2025-07, with the labels that each got.

#345 [Feat/344] notification_type db 초기화 스크립트 추가
  src/main/java/com/gamegoo/gamegoo_v2/scripts/NotificationTypeInitializer.java
Labels: :sparkles: feature

#354 [Fix/352] summonerId 사용하는 API 제거
  src/main/java/com/gamegoo/gamegoo_v2/account/auth/service/AuthFacadeService.java
  src/main/java/com/gamegoo/gamegoo_v2/external/riot/dto/response/RiotInfoResponse.java
  src/main/java/com/gamegoo/gamegoo_v2/external/riot/service/RiotAuthService.java
  src/main/java/com/gamegoo/gamegoo_v2/external/riot/service/RiotFacadeService.java
  src/main/java/com/gamegoo/gamegoo_v2/external/riot/service/RiotInfoService.java
Labels: :bug: bug

#359 [Fix/358] DiscordLogger 버그 해결
  src/main/java/com/gamegoo/gamegoo_v2/core/log/DiscordLogger.java
Labels: :bug: bug

#361 [Refactor/360] 친구목록 조회 API 쿼리 테스트 및 최적화
  build.gradle
  src/main/java/com/gamegoo/gamegoo_v2/account/member/domain/Member.java
  src/main/java/com/gamegoo/gamegoo_v2/account/member/domain/MemberRecentStats.java
  src/main/java/com/gamegoo/gamegoo_v2/core/config/P6SpyConfig.java
  src/main/java/com/gamegoo/gamegoo_v2/social/friend/repository/FriendRepositoryCustomImpl.java
  src/main/resources/application.yml
  src/test/java/com/gamegoo/gamegoo_v2/feature/BanFeatureTest.java
  src/test/java/com/gamegoo/gamegoo_v2/integration/batch/BatchFacadeServiceTest.java
  src/test/java/com/gamegoo/gamegoo_v2/integration/block/BlockFacadeServiceTest.java
  src/test/java/com/gamegoo/gamegoo_v2/integration/chat/ChatFacadeServiceTest.java
  src/test/java/com/gamegoo/gamegoo_v2/integration/friend/FriendFacadeServiceTest.java
  src/test/java/com/gamegoo/gamegoo_v2/integration/friend/FriendRequestFacadeServiceTest.java
  src/test/java/com/gamegoo/gamegoo_v2/integration/manner/MannerFacadeServiceTest.java
  src/test/java/com/gamegoo/gamegoo_v2/integration/member/MemberServiceFacadeTest.java
  src/test/java/com/gamegoo/gamegoo_v2/integration/report/ReportFacadeServiceTest.java
  src/test/java/com/gamegoo/gamegoo_v2/service/batch/BatchServiceTest.java
  src/test/java/com/gamegoo/gamegoo_v2/service/board/BoardServiceTest.java
  src/test/java/com/gamegoo/gamegoo_v2/service/chat/ChatCommandServiceTest.java
  src/test/java/com/gamegoo/gamegoo_v2/service/manner/MannerServiceTest.java
  src/test/java/com/gamegoo/gamegoo_v2/service/matching/MatchingStrategyProcessorTest.java
  src/test/java/com/gamegoo/gamegoo_v2/service/report/ReportServiceTest.java
Labels: :recycle: refactor, :bug: bug

#366 [Refactor/363] 채팅방 목록 조회 API 성능 개선
  src/main/java/com/gamegoo/gamegoo_v2/account/member/repository/MemberRepository.java
  src/main/java/com/gamegoo/gamegoo_v2/account/member/service/MemberService.java
  src/main/java/com/gamegoo/gamegoo_v2/chat/dto/ChatResponseFactory.java
  src/main/java/com/gamegoo/gamegoo_v2/chat/dto/data/ChatroomSummaryDTO.java
  src/main/java/com/gamegoo/gamegoo_v2/chat/repository/ChatRepositoryCustom.java
  src/main/java/com/gamegoo/gamegoo_v2/chat/repository/ChatRepositoryCustomImpl.java
  src/main/java/com/gamegoo/gamegoo_v2/chat/repository/ChatroomRepository.java
  src/main/java/com/gamegoo/gamegoo_v2/chat/repository/MemberChatroomRepository.java
  src/main/java/com/gamegoo/gamegoo_v2/chat/repository/MemberChatroomRepositoryCustom.java
  src/main/java/com/gamegoo/gamegoo_v2/chat/repository/MemberChatroomRepositoryCustomImpl.java
  src/main/java/com/gamegoo/gamegoo_v2/chat/service/ChatFacadeService.java
  src/main/java/com/gamegoo/gamegoo_v2/chat/service/ChatQueryService.java
  src/test/java/com/gamegoo/gamegoo_v2/integration/chat/ChatFacadeServiceTest.java
  src/test/java/com/gamegoo/gamegoo_v2/repository/chat/ChatRepositoryTest.java
  src/test/java/com/gamegoo/gamegoo_v2/repository/chat/MemberChatroomRepositoryTest.java
Labels: :recycle: refactor

#377 [Refactor/367] prometheus 관련 API 로깅 제거
  src/main/java/com/gamegoo/gamegoo_v2/core/log/LoggingFilter.java
Labels: :recycle: refactor

#380 [Fix/279] controller 변수명 중복 수정
  src/main/java/com/gamegoo/gamegoo_v2/account/member/controller/MemberController.java
Labels: :bug: bug

#387 [Fix/386] 신고 목록 조회 및 처리 로직에 비회원 신고 건 반영
  src/main/java/com/gamegoo/gamegoo_v2/content/report/dto/response/ReportListResponse.java
  src/main/java/com/gamegoo/gamegoo_v2/content/report/service/ReportFacadeService.java
Labels: :bug: bug

#388 [Fix/382] 채팅방 목록 조회 Native Query 수정
  src/main/java/com/gamegoo/gamegoo_v2/chat/repository/ChatroomRepository.java
Labels: :bug: bug

#393 [Refactor/392] JWT 검증 filter에서 DB 조회 로직 제외
  src/main/java/com/gamegoo/gamegoo_v2/account/auth/annotation/resolver/AuthMemberArgumentResolver.java
  src/main/java/com/gamegoo/gamegoo_v2/account/auth/controller/AuthController.java
  src/main/java/com/gamegoo/gamegoo_v2/account/auth/jwt/JwtProvider.java
  src/main/java/com/gamegoo/gamegoo_v2/account/auth/security/CustomUserDetails.java
  src/main/java/com/gamegoo/gamegoo_v2/account/auth/security/JwtAuthFilter.java
  src/main/java/com/gamegoo/gamegoo_v2/account/auth/service/AuthFacadeService.java
  src/main/java/com/gamegoo/gamegoo_v2/core/config/SecurityConfig.java
  src/main/java/com/gamegoo/gamegoo_v2/core/exception/common/ExceptionAdvice.java
  src/main/java/com/gamegoo/gamegoo_v2/external/riot/service/RiotFacadeService.java
  src/test/java/com/gamegoo/gamegoo_v2/integration/auth/AuthFacadeServiceTest.java
Labels: :recycle: refactor
