Repository Gamegoo-repo/Gamegoo-Server-v2, pull requests merged in 2025-02, with the labels that each got.

#191 [Feat/190] 끌올 기능 API 구현
  src/main/java/com/gamegoo/gamegoo_v2/content/board/controller/BoardController.java
  src/main/java/com/gamegoo/gamegoo_v2/content/board/domain/Board.java
  src/main/java/com/gamegoo/gamegoo_v2/content/board/dto/response/BoardBumpResponse.java
  src/main/java/com/gamegoo/gamegoo_v2/content/board/service/BoardFacadeService.java
  src/main/java/com/gamegoo/gamegoo_v2/content/board/service/BoardService.java
  src/main/java/com/gamegoo/gamegoo_v2/core/exception/common/ErrorCode.java
Labels: :sparkles: feature

#189 [Feat/186] 매칭 우선순위 API 구현
  src/main/java/com/gamegoo/gamegoo_v2/account/member/domain/Member.java
  src/main/java/com/gamegoo/gamegoo_v2/account/member/domain/Mike.java
  src/main/java/com/gamegoo/gamegoo_v2/account/member/service/MemberFacadeService.java
  src/main/java/com/gamegoo/gamegoo_v2/account/member/service/MemberGameStyleService.java
  src/main/java/com/gamegoo/gamegoo_v2/account/member/service/MemberService.java
  src/main/java/com/gamegoo/gamegoo_v2/matching/Controller/MatchingController.java
  src/main/java/com/gamegoo/gamegoo_v2/matching/domain/MatchingRecord.java
  src/main/java/com/gamegoo/gamegoo_v2/matching/dto/PriorityValue.java
  src/main/java/com/gamegoo/gamegoo_v2/matching/dto/request/InitializingMatchingRequest.java
  src/main/java/com/gamegoo/gamegoo_v2/matching/dto/response/MatchingMemberInfoResponse.java
  src/main/java/com/gamegoo/gamegoo_v2/matching/dto/response/PriorityListResponse.java
  src/main/java/com/gamegoo/gamegoo_v2/matching/repository/MatchingRecordRepository.java
  src/main/java/com/gamegoo/gamegoo_v2/matching/repository/MatchingRecordRepositoryCustom.java
  src/main/java/com/gamegoo/gamegoo_v2/matching/repository/MatchingRecordRepositoryCustomImpl.java
  src/main/java/com/gamegoo/gamegoo_v2/matching/service/MatchingFacadeService.java
  src/main/java/com/gamegoo/gamegoo_v2/matching/service/MatchingScoreCalculator.java
  src/main/java/com/gamegoo/gamegoo_v2/matching/service/MatchingService.java
  src/main/java/com/gamegoo/gamegoo_v2/matching/service/MatchingStrategyProcessor.java
  src/test/java/com/gamegoo/gamegoo_v2/integration/matching/MatchingFacadeServiceTest.java
  src/test/java/com/gamegoo/gamegoo_v2/service/matching/MatchingScoreCalculatorTest.java
  src/test/java/com/gamegoo/gamegoo_v2/service/matching/MatchingServiceTest.java
  src/test/java/com/gamegoo/gamegoo_v2/service/matching/MatchingStrategyProcessorTest.java
Labels: :sparkles: feature

#195 [Feat/194] 자유랭크 티어 정보 조회
  src/main/java/com/gamegoo/gamegoo_v2/account/auth/service/AuthFacadeService.java
  src/main/java/com/gamegoo/gamegoo_v2/account/member/domain/Member.java
  src/main/java/com/gamegoo/gamegoo_v2/account/member/dto/response/MyProfileResponse.java
  src/main/java/com/gamegoo/gamegoo_v2/account/member/dto/response/OtherProfileResponse.java
  src/main/java/com/gamegoo/gamegoo_v2/account/member/service/MemberService.java
  src/main/java/com/gamegoo/gamegoo_v2/content/board/domain/Board.java
  src/main/java/com/gamegoo/gamegoo_v2/content/board/dto/response/BoardByIdResponse.java
  src/main/java/com/gamegoo/gamegoo_v2/content/board/dto/response/BoardByIdResponseForMember.java
  src/main/java/com/gamegoo/gamegoo_v2/content/board/dto/response/BoardInsertResponse.java
  src/main/java/com/gamegoo/gamegoo_v2/content/board/dto/response/BoardListResponse.java
  src/main/java/com/gamegoo/gamegoo_v2/content/board/dto/response/BoardUpdateResponse.java
  src/main/java/com/gamegoo/gamegoo_v2/content/board/dto/response/MyBoardListResponse.java
  src/main/java/com/gamegoo/gamegoo_v2/content/board/repository/BoardRepository.java
  src/main/java/com/gamegoo/gamegoo_v2/external/riot/dto/TierDetails.java
  src/main/java/com/gamegoo/gamegoo_v2/external/riot/service/RiotInfoService.java
  src/main/java/com/gamegoo/gamegoo_v2/matching/domain/MatchingRecord.java
  src/main/java/com/gamegoo/gamegoo_v2/matching/dto/response/MatchingMemberInfoResponse.java
  src/main/java/com/gamegoo/gamegoo_v2/matching/repository/MatchingRecordRepositoryCustomImpl.java
  src/main/java/com/gamegoo/gamegoo_v2/matching/service/MatchingStrategyProcessor.java
  src/test/java/com/gamegoo/gamegoo_v2/controller/ControllerTestSupport.java
  src/test/java/com/gamegoo/gamegoo_v2/integration/auth/AuthFacadeServiceTest.java
  src/test/java/com/gamegoo/gamegoo_v2/integration/auth/PasswordFacadeServiceTest.java
  src/test/java/com/gamegoo/gamegoo_v2/integration/batch/BatchFacadeServiceTest.java
  src/test/java/com/gamegoo/gamegoo_v2/integration/block/BlockFacadeServiceTest.java
  src/test/java/com/gamegoo/gamegoo_v2/integration/chat/ChatFacadeServiceTest.java
  src/test/java/com/gamegoo/gamegoo_v2/integration/email/EmailFacadeServiceTest.java
  src/test/java/com/gamegoo/gamegoo_v2/integration/friend/FriendFacadeServiceTest.java
  src/test/java/com/gamegoo/gamegoo_v2/integration/friend/FriendRequestFacadeServiceTest.java
  src/test/java/com/gamegoo/gamegoo_v2/integration/manner/MannerFacadeServiceTest.java
  src/test/java/com/gamegoo/gamegoo_v2/integration/matching/MatchingFacadeServiceTest.java
  src/test/java/com/gamegoo/gamegoo_v2/integration/member/MemberServiceFacadeTest.java
  src/test/java/com/gamegoo/gamegoo_v2/integration/notification/NotificationFacadeServiceTest.java
  src/test/java/com/gamegoo/gamegoo_v2/integration/report/ReportFacadeServiceTest.java
  src/test/java/com/gamegoo/gamegoo_v2/repository/RepositoryTestSupport.java
  src/test/java/com/gamegoo/gamegoo_v2/service/batch/BatchServiceTest.java
  src/test/java/com/gamegoo/gamegoo_v2/service/chat/ChatCommandServiceTest.java
  src/test/java/com/gamegoo/gamegoo_v2/service/friend/FriendServiceTest.java
  src/test/java/com/gamegoo/gamegoo_v2/service/manner/MannerServiceTest.java
  src/test/java/com/gamegoo/gamegoo_v2/service/matching/MatchingServiceTest.java
  src/test/java/com/gamegoo/gamegoo_v2/service/matching/MatchingStrategyProcessorTest.java
  src/test/java/com/gamegoo/gamegoo_v2/service/notification/NotificationServiceTest.java
  src/test/java/com/gamegoo/gamegoo_v2/unit/MatchingScoreCalculatorTest.java
  src/test/java/com/gamegoo/gamegoo_v2/unit/factory/ChatResponseFactoryTest.java
Labels: :sparkles: feature

#198 [Feat/196] 매칭 status 변경 API 구현
  src/main/java/com/gamegoo/gamegoo_v2/account/member/domain/Member.java
  src/main/java/com/gamegoo/gamegoo_v2/account/member/dto/response/MyProfileResponse.java
  src/main/java/com/gamegoo/gamegoo_v2/account/member/dto/response/OtherProfileResponse.java
  src/main/java/com/gamegoo/gamegoo_v2/core/exception/MatchingException.java
  src/main/java/com/gamegoo/gamegoo_v2/core/exception/common/ErrorCode.java
  src/main/java/com/gamegoo/gamegoo_v2/matching/controller/MatchingController.java
  src/main/java/com/gamegoo/gamegoo_v2/matching/domain/MatchingRecord.java
  src/main/java/com/gamegoo/gamegoo_v2/matching/dto/request/ModifyMyMatchingStatusRequest.java
  src/main/java/com/gamegoo/gamegoo_v2/matching/dto/response/MatchingMemberInfoResponse.java
  src/main/java/com/gamegoo/gamegoo_v2/matching/repository/MatchingRecordRepository.java
  src/main/java/com/gamegoo/gamegoo_v2/matching/repository/MatchingRecordRepositoryCustom.java
  src/main/java/com/gamegoo/gamegoo_v2/matching/repository/MatchingRecordRepositoryCustomImpl.java
  src/main/java/com/gamegoo/gamegoo_v2/matching/service/MatchingFacadeService.java
  src/main/java/com/gamegoo/gamegoo_v2/matching/service/MatchingService.java
  src/main/java/com/gamegoo/gamegoo_v2/matching/service/MatchingStrategyProcessor.java
  src/test/java/com/gamegoo/gamegoo_v2/integration/matching/MatchingFacadeServiceTest.java
  src/test/java/com/gamegoo/gamegoo_v2/integration/member/MemberServiceFacadeTest.java
  src/test/java/com/gamegoo/gamegoo_v2/service/matching/MatchingStrategyProcessorTest.java
Labels: :sparkles: feature, ✅ test

#197 [Feat/192] 게시판 목록에서 메모, 끌올 시간 불러오기
  src/main/java/com/gamegoo/gamegoo_v2/content/board/dto/response/BoardListResponse.java
Labels: :sparkles: feature

#202 [Feat/201] health check API 구현
  src/main/java/com/gamegoo/gamegoo_v2/HomeController.java
  src/main/java/com/gamegoo/gamegoo_v2/core/config/SecurityConfig.java
  src/main/resources/excluded-paths.yml
Labels: :sparkles: feature

#204 [Feat/200] 게시판 자유랭크 반영, 자유랭크 기반 게시물 조회
  src/main/java/com/gamegoo/gamegoo_v2/content/board/controller/BoardController.java
  src/main/java/com/gamegoo/gamegoo_v2/content/board/dto/response/BoardByIdResponse.java
  src/main/java/com/gamegoo/gamegoo_v2/content/board/dto/response/BoardByIdResponseForMember.java
  src/main/java/com/gamegoo/gamegoo_v2/content/board/dto/response/BoardInsertResponse.java
  src/main/java/com/gamegoo/gamegoo_v2/content/board/dto/response/BoardListResponse.java
  src/main/java/com/gamegoo/gamegoo_v2/content/board/dto/response/BoardUpdateResponse.java
  src/main/java/com/gamegoo/gamegoo_v2/content/board/dto/response/MyBoardListResponse.java
  src/main/java/com/gamegoo/gamegoo_v2/content/board/repository/BoardRepository.java
  src/main/java/com/gamegoo/gamegoo_v2/content/board/service/BoardFacadeService.java
  src/main/java/com/gamegoo/gamegoo_v2/content/board/service/BoardService.java
Labels: :sparkles: feature

#203 [Feat/199] 상대방과 나 MatchingStatus 변경
  src/main/java/com/gamegoo/gamegoo_v2/core/exception/common/ErrorCode.java
  src/main/java/com/gamegoo/gamegoo_v2/matching/controller/MatchingController.java
  src/main/java/com/gamegoo/gamegoo_v2/matching/domain/MatchingRecord.java
  src/main/java/com/gamegoo/gamegoo_v2/matching/dto/request/ModifyMatchingStatusRequest.java
  src/main/java/com/gamegoo/gamegoo_v2/matching/repository/MatchingRecordRepositoryCustom.java
  src/main/java/com/gamegoo/gamegoo_v2/matching/repository/MatchingRecordRepositoryCustomImpl.java
  src/main/java/com/gamegoo/gamegoo_v2/matching/service/MatchingFacadeService.java
  src/main/java/com/gamegoo/gamegoo_v2/matching/service/MatchingService.java
  src/test/java/com/gamegoo/gamegoo_v2/integration/matching/MatchingFacadeServiceTest.java
Labels: :sparkles: feature, ✅ test

#213 [Fix/212] 회원용 게시물 조회 변수 불일치 수정
  src/main/java/com/gamegoo/gamegoo_v2/content/board/dto/response/BoardByIdResponseForMember.java
Labels: :bug: bug

#215 [Fix/214] 게시물 조회 시 티어 파라미터 통합
  src/main/java/com/gamegoo/gamegoo_v2/content/board/controller/BoardController.java
  src/main/java/com/gamegoo/gamegoo_v2/content/board/dto/response/BoardByIdResponse.java
  src/main/java/com/gamegoo/gamegoo_v2/content/board/dto/response/BoardByIdResponseForMember.java
  src/main/java/com/gamegoo/gamegoo_v2/content/board/dto/response/BoardInsertResponse.java
  src/main/java/com/gamegoo/gamegoo_v2/content/board/dto/response/BoardListResponse.java
  src/main/java/com/gamegoo/gamegoo_v2/content/board/dto/response/BoardUpdateResponse.java
  src/main/java/com/gamegoo/gamegoo_v2/content/board/dto/response/MyBoardListResponse.java
  src/main/java/com/gamegoo/gamegoo_v2/content/board/repository/BoardRepository.java
  src/main/java/com/gamegoo/gamegoo_v2/content/board/service/BoardFacadeService.java
  src/main/java/com/gamegoo/gamegoo_v2/content/board/service/BoardService.java
Labels: :bug: bug

#210 [Feat/209] 매칭 found API 및 테스트 구현
  src/main/java/com/gamegoo/gamegoo_v2/core/common/validator/MatchingValidator.java
  src/main/java/com/gamegoo/gamegoo_v2/core/exception/common/ErrorCode.java
  src/main/java/com/gamegoo/gamegoo_v2/matching/controller/MatchingController.java
  src/main/java/com/gamegoo/gamegoo_v2/matching/domain/MatchingRecord.java
  src/main/java/com/gamegoo/gamegoo_v2/matching/dto/request/MatchingFoundRequest.java
  src/main/java/com/gamegoo/gamegoo_v2/matching/dto/response/MatchingFoundResponse.java
  src/main/java/com/gamegoo/gamegoo_v2/matching/service/MatchingFacadeService.java
  src/main/java/com/gamegoo/gamegoo_v2/matching/service/MatchingService.java
  src/test/java/com/gamegoo/gamegoo_v2/integration/matching/MatchingFacadeServiceTest.java
Labels: :sparkles: feature, ✅ test

#221 [Feat/211] 매칭 빠른대전 티어 기획 수정 반영
  src/main/java/com/gamegoo/gamegoo_v2/matching/domain/MatchingRecord.java
  src/main/java/com/gamegoo/gamegoo_v2/matching/service/MatchingStrategyProcessor.java
  src/test/java/com/gamegoo/gamegoo_v2/integration/member/MemberServiceFacadeTest.java
  src/test/java/com/gamegoo/gamegoo_v2/service/matching/MatchingStrategyProcessorTest.java
Labels: :sparkles: feature

#219 [Feat/218] 원하는 포지션 여러개 선택 가능
  src/main/java/com/gamegoo/gamegoo_v2/content/board/domain/Board.java
  src/main/java/com/gamegoo/gamegoo_v2/content/board/dto/request/BoardInsertRequest.java
  src/main/java/com/gamegoo/gamegoo_v2/content/board/dto/request/BoardUpdateRequest.java
  src/main/java/com/gamegoo/gamegoo_v2/content/board/dto/response/BoardByIdResponse.java
  src/main/java/com/gamegoo/gamegoo_v2/content/board/dto/response/BoardByIdResponseForMember.java
  src/main/java/com/gamegoo/gamegoo_v2/content/board/dto/response/BoardInsertResponse.java
  src/main/java/com/gamegoo/gamegoo_v2/content/board/dto/response/BoardListResponse.java
  src/main/java/com/gamegoo/gamegoo_v2/content/board/dto/response/BoardUpdateResponse.java
  src/test/java/com/gamegoo/gamegoo_v2/integration/chat/ChatFacadeServiceTest.java
  src/test/java/com/gamegoo/gamegoo_v2/integration/report/ReportFacadeServiceTest.java
  src/test/java/com/gamegoo/gamegoo_v2/service/chat/ChatCommandServiceTest.java
Labels: :sparkles: feature

#225 [Feat/223] 서버 내부 에러 발생 시 디스코드 알림 전송
  .github/workflows/github_actions.yml
  build.gradle
  src/main/resources/application.yml
  src/main/resources/logback-spring.xml
Labels: :sparkles: feature

#227 [Fix/222] 매칭 리스트 조회 시 중복 Id 조회되는 문제 해결 + 프로필 조회 수정
  src/main/java/com/gamegoo/gamegoo_v2/account/member/dto/response/MyProfileResponse.java
  src/main/java/com/gamegoo/gamegoo_v2/account/member/dto/response/OtherProfileResponse.java
  src/main/java/com/gamegoo/gamegoo_v2/account/member/service/MemberFacadeService.java
  src/main/java/com/gamegoo/gamegoo_v2/matching/controller/MatchingController.java
  src/main/java/com/gamegoo/gamegoo_v2/matching/repository/MatchingRecordRepositoryCustom.java
  src/main/java/com/gamegoo/gamegoo_v2/matching/repository/MatchingRecordRepositoryCustomImpl.java
  src/main/java/com/gamegoo/gamegoo_v2/matching/service/MatchingFacadeService.java
  src/main/java/com/gamegoo/gamegoo_v2/matching/service/MatchingService.java
  src/test/java/com/gamegoo/gamegoo_v2/integration/matching/MatchingFacadeServiceTest.java
  src/test/java/com/gamegoo/gamegoo_v2/integration/member/MemberServiceFacadeTest.java
  src/test/java/com/gamegoo/gamegoo_v2/service/matching/MatchingServiceTest.java
Labels: :bug: bug

#231 [Cicd/230] 개발/운영 서버 환경 분리
  .github/workflows/deploy-dev.yml
  .github/workflows/deploy-prod.yml
  Dockerfile-dev
  Dockerfile-prod
  src/main/resources/application.yml
  src/main/resources/logback-spring.xml
Labels: :construction_worker: cicd

#233 [Feat/232] 신고 등록 쿨타임 기능 구현
  src/main/java/com/gamegoo/gamegoo_v2/content/report/repository/ReportRepository.java
  src/main/java/com/gamegoo/gamegoo_v2/content/report/service/ReportFacadeService.java
  src/main/java/com/gamegoo/gamegoo_v2/content/report/service/ReportService.java
  src/main/java/com/gamegoo/gamegoo_v2/core/config/SecurityConfig.java
  src/main/java/com/gamegoo/gamegoo_v2/core/exception/common/ErrorCode.java
  src/test/java/com/gamegoo/gamegoo_v2/integration/report/ReportFacadeServiceTest.java
Labels: :sparkles: feature

#235 [Cicd/234] 개발 서버 이전
  .github/workflows/deploy-dev.yml
  Dockerfile-dev
  src/main/java/com/gamegoo/gamegoo_v2/core/config/SshDataSourceConfig.java
  src/main/java/com/gamegoo/gamegoo_v2/core/config/SshTunnelingInitializer.java
  src/main/resources/application.yml
Labels: :construction_worker: cicd
