Repository Gamegoo-repo/Gamegoo-Server-v2, pull requests merged in 2025-01, with the labels that each got.

#120 [Fix/120] git 충돌 해결
  src/main/java/com/gamegoo/gamegoo_v2/account/auth/service/AuthFacadeService.java
  src/main/java/com/gamegoo/gamegoo_v2/account/auth/service/PasswordService.java
  src/test/java/com/gamegoo/gamegoo_v2/integration/auth/AuthFacadeServiceTest.java
Labels: :sparkles: feature, ✅ test, :bug: bug

#115 [Feat/104] 채팅방 목록 조회 API 구현 및 테스트
  src/main/java/com/gamegoo/gamegoo_v2/chat/controller/ChatController.java
  src/main/java/com/gamegoo/gamegoo_v2/chat/domain/Chatroom.java
  src/main/java/com/gamegoo/gamegoo_v2/chat/dto/ChatResponseFactory.java
  src/main/java/com/gamegoo/gamegoo_v2/chat/dto/response/ChatroomListResponse.java
  src/main/java/com/gamegoo/gamegoo_v2/chat/dto/response/ChatroomResponse.java
  src/main/java/com/gamegoo/gamegoo_v2/chat/repository/ChatRepositoryCustom.java
  src/main/java/com/gamegoo/gamegoo_v2/chat/repository/ChatRepositoryCustomImpl.java
  src/main/java/com/gamegoo/gamegoo_v2/chat/repository/MemberChatroomRepository.java
  src/main/java/com/gamegoo/gamegoo_v2/chat/repository/MemberChatroomRepositoryCustom.java
  src/main/java/com/gamegoo/gamegoo_v2/chat/repository/MemberChatroomRepositoryCustomImpl.java
  src/main/java/com/gamegoo/gamegoo_v2/chat/service/ChatCommandService.java
  src/main/java/com/gamegoo/gamegoo_v2/chat/service/ChatFacadeService.java
  src/main/java/com/gamegoo/gamegoo_v2/chat/service/ChatQueryService.java
  src/main/java/com/gamegoo/gamegoo_v2/social/block/repository/BlockRepository.java
  src/main/java/com/gamegoo/gamegoo_v2/social/block/repository/BlockRepositoryCustom.java
  src/main/java/com/gamegoo/gamegoo_v2/social/block/repository/BlockRepositoryCustomImpl.java
  src/main/java/com/gamegoo/gamegoo_v2/social/block/service/BlockService.java
  src/main/java/com/gamegoo/gamegoo_v2/social/friend/controller/FriendController.java
  src/main/java/com/gamegoo/gamegoo_v2/social/friend/repository/FriendRepositoryCustom.java
  src/main/java/com/gamegoo/gamegoo_v2/social/friend/repository/FriendRepositoryCustomImpl.java
  src/main/java/com/gamegoo/gamegoo_v2/social/friend/repository/FriendRequestRepository.java
  src/main/java/com/gamegoo/gamegoo_v2/social/friend/service/FriendService.java
  src/test/java/com/gamegoo/gamegoo_v2/controller/chat/ChatControllerTest.java
  src/test/java/com/gamegoo/gamegoo_v2/controller/friend/FriendControllerTest.java
  src/test/java/com/gamegoo/gamegoo_v2/integration/chat/ChatFacadeServiceTest.java
  src/test/java/com/gamegoo/gamegoo_v2/repository/block/BlockRepositoryTest.java
  src/test/java/com/gamegoo/gamegoo_v2/repository/chat/ChatRepositoryTest.java
  src/test/java/com/gamegoo/gamegoo_v2/repository/chat/MemberChatroomRepositoryTest.java
  src/test/java/com/gamegoo/gamegoo_v2/repository/friend/FriendRepositoryTest.java
  src/test/java/com/gamegoo/gamegoo_v2/service/friend/FriendServiceTest.java
Labels: :sparkles: feature, :recycle: refactor, ✅ test

#124 [Refactor/122] javadoc 주석 작성 및 코드 수정
  src/main/java/com/gamegoo/gamegoo_v2/chat/repository/ChatRepositoryCustom.java
  src/main/java/com/gamegoo/gamegoo_v2/chat/repository/ChatroomRepositoryCustom.java
  src/main/java/com/gamegoo/gamegoo_v2/chat/repository/MemberChatroomRepositoryCustom.java
  src/main/java/com/gamegoo/gamegoo_v2/chat/service/ChatCommandService.java
  src/main/java/com/gamegoo/gamegoo_v2/chat/service/ChatFacadeService.java
  src/main/java/com/gamegoo/gamegoo_v2/chat/service/ChatQueryService.java
  src/main/java/com/gamegoo/gamegoo_v2/core/common/validator/BaseValidator.java
  src/main/java/com/gamegoo/gamegoo_v2/core/common/validator/BlockValidator.java
  src/main/java/com/gamegoo/gamegoo_v2/core/common/validator/ChatValidator.java
  src/main/java/com/gamegoo/gamegoo_v2/core/common/validator/FriendValidator.java
  src/main/java/com/gamegoo/gamegoo_v2/core/common/validator/MemberValidator.java
  src/main/java/com/gamegoo/gamegoo_v2/core/event/listener/FriendRequestEventListener.java
  src/main/java/com/gamegoo/gamegoo_v2/core/event/listener/SocketEventListener.java
  src/main/java/com/gamegoo/gamegoo_v2/core/exception/common/ErrorCode.java
  src/main/java/com/gamegoo/gamegoo_v2/external/socket/SocketService.java
  src/main/java/com/gamegoo/gamegoo_v2/notification/repository/NotificationRepositoryCustom.java
  src/main/java/com/gamegoo/gamegoo_v2/notification/service/NotificationFacadeService.java
  src/main/java/com/gamegoo/gamegoo_v2/notification/service/NotificationService.java
  src/main/java/com/gamegoo/gamegoo_v2/social/block/dto/BlockListResponse.java
  src/main/java/com/gamegoo/gamegoo_v2/social/block/repository/BlockRepositoryCustom.java
  src/main/java/com/gamegoo/gamegoo_v2/social/block/service/BlockFacadeService.java
  src/main/java/com/gamegoo/gamegoo_v2/social/block/service/BlockService.java
  src/main/java/com/gamegoo/gamegoo_v2/social/friend/repository/FriendRepositoryCustom.java
  src/main/java/com/gamegoo/gamegoo_v2/social/friend/service/FriendFacadeService.java
  src/main/java/com/gamegoo/gamegoo_v2/social/friend/service/FriendService.java
Labels: :recycle: refactor, :memo: docs

#123 [Feat/121] 리프레시 토큰 업데이트 API 및 Test 구현
  src/main/java/com/gamegoo/gamegoo_v2/account/auth/controller/AuthController.java
  src/main/java/com/gamegoo/gamegoo_v2/account/auth/dto/request/RefreshTokenRequest.java
  src/main/java/com/gamegoo/gamegoo_v2/account/auth/dto/response/RefreshTokenResponse.java
  src/main/java/com/gamegoo/gamegoo_v2/account/auth/repository/RefreshTokenRepository.java
  src/main/java/com/gamegoo/gamegoo_v2/account/auth/service/AuthFacadeService.java
  src/main/java/com/gamegoo/gamegoo_v2/account/auth/service/AuthService.java
  src/main/java/com/gamegoo/gamegoo_v2/core/config/WebConfig.java
  src/main/java/com/gamegoo/gamegoo_v2/core/exception/common/ErrorCode.java
  src/test/java/com/gamegoo/gamegoo_v2/integration/auth/AuthFacadeServiceTest.java
Labels: :sparkles: feature, ✅ test

#131 [refactor/130] 회원 관련 코드 컨벤션 수정
  src/main/java/com/gamegoo/gamegoo_v2/account/auth/controller/PasswordController.java
  src/main/java/com/gamegoo/gamegoo_v2/account/auth/service/AuthFacadeService.java
  src/main/java/com/gamegoo/gamegoo_v2/account/auth/service/PasswordFacadeService.java
  src/main/java/com/gamegoo/gamegoo_v2/account/email/controller/EmailController.java
  src/main/java/com/gamegoo/gamegoo_v2/account/email/service/EmailFacadeService.java
  src/main/java/com/gamegoo/gamegoo_v2/account/email/service/EmailService.java
  src/main/java/com/gamegoo/gamegoo_v2/account/member/dto/response/OtherProfileResponse.java
  src/main/java/com/gamegoo/gamegoo_v2/account/member/service/MemberFacadeService.java
  src/main/java/com/gamegoo/gamegoo_v2/account/member/service/MemberService.java
  src/main/java/com/gamegoo/gamegoo_v2/external/riot/controller/RiotController.java
  src/main/java/com/gamegoo/gamegoo_v2/external/riot/service/RiotAuthService.java
  src/main/java/com/gamegoo/gamegoo_v2/external/riot/service/RiotFacadeService.java
  src/main/java/com/gamegoo/gamegoo_v2/external/riot/service/RiotInfoService.java
  src/main/java/com/gamegoo/gamegoo_v2/external/riot/service/RiotRecordService.java
  src/main/java/com/gamegoo/gamegoo_v2/utils/EmailTemplateProcessor.java
  src/main/java/com/gamegoo/gamegoo_v2/utils/PasswordUtil.java
  src/main/java/com/gamegoo/gamegoo_v2/utils/RandomCodeGeneratorUtil.java
  src/test/java/com/gamegoo/gamegoo_v2/integration/member/MemberServiceFacadeTest.java
Labels: :recycle: refactor

#126 [Feat/116] 매칭을 통한 채팅방 시작 메소드 구현 및 테스트
  src/main/java/com/gamegoo/gamegoo_v2/chat/service/ChatCommandService.java
  src/main/java/com/gamegoo/gamegoo_v2/matching/service/MatchingFacadeService.java
  src/main/java/com/gamegoo/gamegoo_v2/notification/controller/NotificationController.java
  src/test/java/com/gamegoo/gamegoo_v2/integration/matching/MatchingFacadeServiceTest.java
Labels: :sparkles: feature, ✅ test

#128 [Feat/127] 친구, 채팅 관련 internal API 구현 및 테스트
  src/main/java/com/gamegoo/gamegoo_v2/chat/controller/ChatController.java
  src/main/java/com/gamegoo/gamegoo_v2/chat/controller/ChatInternalController.java
  src/main/java/com/gamegoo/gamegoo_v2/chat/service/ChatFacadeService.java
  src/main/java/com/gamegoo/gamegoo_v2/core/config/WebConfig.java
  src/main/java/com/gamegoo/gamegoo_v2/social/friend/controller/FriendController.java
  src/main/java/com/gamegoo/gamegoo_v2/social/friend/controller/FriendInternalController.java
  src/main/java/com/gamegoo/gamegoo_v2/social/friend/service/FriendFacadeService.java
  src/test/java/com/gamegoo/gamegoo_v2/controller/chat/ChatControllerTest.java
  src/test/java/com/gamegoo/gamegoo_v2/controller/friend/FriendControllerTest.java
  src/test/java/com/gamegoo/gamegoo_v2/controller/internal/InternalControllerTest.java
  src/test/java/com/gamegoo/gamegoo_v2/integration/chat/ChatFacadeServiceTest.java
  src/test/java/com/gamegoo/gamegoo_v2/integration/friend/FriendFacadeServiceTest.java
Labels: :sparkles: feature, ✅ test

#125 [Feat/117] 게시물 목록 조회
  src/main/java/com/gamegoo/gamegoo_v2/content/board/controller/BoardController.java
  src/main/java/com/gamegoo/gamegoo_v2/content/board/dto/response/BoardListResponse.java
  src/main/java/com/gamegoo/gamegoo_v2/content/board/dto/response/BoardResponse.java
  src/main/java/com/gamegoo/gamegoo_v2/content/board/dto/response/ChampionResponse.java
  src/main/java/com/gamegoo/gamegoo_v2/content/board/repository/BoardRepository.java
  src/main/java/com/gamegoo/gamegoo_v2/content/board/service/BoardFacadeService.java
  src/main/java/com/gamegoo/gamegoo_v2/content/board/service/BoardService.java
  src/main/java/com/gamegoo/gamegoo_v2/core/exception/common/ErrorCode.java
Labels: :sparkles: feature

#137 [Fix/135] CORS 에러 수정
  .github/workflows/github_actions.yml
  src/main/java/com/gamegoo/gamegoo_v2/account/auth/jwt/JwtInterceptor.java
  src/main/java/com/gamegoo/gamegoo_v2/core/config/WebConfig.java
Labels: :construction_worker: cicd, :bug: bug

#139 [Feat/138] 비매너 평가 등록 API 구현 및 테스트
  src/main/java/com/gamegoo/gamegoo_v2/core/common/annotation/NotDuplicated.java
  src/main/java/com/gamegoo/gamegoo_v2/core/common/annotationValidator/NotDuplicatedAnnotationValidator.java
  src/main/java/com/gamegoo/gamegoo_v2/social/manner/controller/MannerController.java
  src/main/java/com/gamegoo/gamegoo_v2/social/manner/dto/request/MannerInsertRequest.java
  src/main/java/com/gamegoo/gamegoo_v2/social/manner/service/MannerFacadeService.java
  src/main/java/com/gamegoo/gamegoo_v2/social/manner/service/MannerService.java
  src/test/java/com/gamegoo/gamegoo_v2/controller/manner/MannerControllerTest.java
  src/test/java/com/gamegoo/gamegoo_v2/integration/manner/MannerFacadeServiceTest.java
Labels: :sparkles: feature, ✅ test

#144 [fix/143] 테스트에서 토큰 검증하기 수정
  src/test/java/com/gamegoo/gamegoo_v2/integration/auth/AuthFacadeServiceTest.java
Labels: ✅ test, :bug: bug

#147 [Feat/142] 비회원 게시물 조회 API
  src/main/java/com/gamegoo/gamegoo_v2/content/board/controller/BoardController.java
  src/main/java/com/gamegoo/gamegoo_v2/content/board/dto/response/BoardByIdResponse.java
  src/main/java/com/gamegoo/gamegoo_v2/content/board/service/BoardFacadeService.java
  src/main/java/com/gamegoo/gamegoo_v2/core/config/WebConfig.java
Labels: :sparkles: feature

#150 [Feat/149] 매너 정보 조회 API 구현 및 테스트
  src/main/java/com/gamegoo/gamegoo_v2/account/member/domain/Member.java
  src/main/java/com/gamegoo/gamegoo_v2/social/manner/controller/MannerController.java
  src/main/java/com/gamegoo/gamegoo_v2/social/manner/dto/response/MannerKeywordResponse.java
  src/main/java/com/gamegoo/gamegoo_v2/social/manner/dto/response/MannerResponse.java
  src/main/java/com/gamegoo/gamegoo_v2/social/manner/repository/MannerRatingKeywordRepository.java
  src/main/java/com/gamegoo/gamegoo_v2/social/manner/repository/MannerRatingKeywordRepositoryCustom.java
  src/main/java/com/gamegoo/gamegoo_v2/social/manner/repository/MannerRatingKeywordRepositoryCustomImpl.java
  src/main/java/com/gamegoo/gamegoo_v2/social/manner/repository/MannerRatingRepository.java
  src/main/java/com/gamegoo/gamegoo_v2/social/manner/service/MannerFacadeService.java
  src/main/java/com/gamegoo/gamegoo_v2/social/manner/service/MannerService.java
  src/test/java/com/gamegoo/gamegoo_v2/controller/manner/MannerControllerTest.java
  src/test/java/com/gamegoo/gamegoo_v2/integration/manner/MannerFacadeServiceTest.java
  src/test/java/com/gamegoo/gamegoo_v2/repository/manner/MannerRepositoryTest.java
Labels: :sparkles: feature, ✅ test

#155 [Fix/153] 친구 목록 조회 페이징 로직 제거
  src/main/java/com/gamegoo/gamegoo_v2/social/friend/controller/FriendController.java
  src/main/java/com/gamegoo/gamegoo_v2/social/friend/dto/FriendListResponse.java
  src/main/java/com/gamegoo/gamegoo_v2/social/friend/repository/FriendRepositoryCustom.java
  src/main/java/com/gamegoo/gamegoo_v2/social/friend/repository/FriendRepositoryCustomImpl.java
  src/main/java/com/gamegoo/gamegoo_v2/social/friend/service/FriendFacadeService.java
  src/main/java/com/gamegoo/gamegoo_v2/social/friend/service/FriendService.java
  src/test/java/com/gamegoo/gamegoo_v2/controller/friend/FriendControllerTest.java
  src/test/java/com/gamegoo/gamegoo_v2/integration/friend/FriendFacadeServiceTest.java
  src/test/java/com/gamegoo/gamegoo_v2/repository/friend/FriendRepositoryTest.java
Labels: :bug: bug

#157 [Feat/151] 회원 신고 등록 API 구현 및 테스트
  src/main/java/com/gamegoo/gamegoo_v2/content/report/controller/ReportController.java
  src/main/java/com/gamegoo/gamegoo_v2/content/report/domain/Report.java
  src/main/java/com/gamegoo/gamegoo_v2/content/report/domain/ReportPath.java
  src/main/java/com/gamegoo/gamegoo_v2/content/report/domain/ReportType.java
  src/main/java/com/gamegoo/gamegoo_v2/content/report/domain/ReportTypeMapping.java
  src/main/java/com/gamegoo/gamegoo_v2/content/report/domain/domain/Report.java
  src/main/java/com/gamegoo/gamegoo_v2/content/report/dto/request/ReportRequest.java
  src/main/java/com/gamegoo/gamegoo_v2/content/report/dto/response/ReportInsertResponse.java
  src/main/java/com/gamegoo/gamegoo_v2/content/report/repository/ReportRepository.java
  src/main/java/com/gamegoo/gamegoo_v2/content/report/repository/ReportTypeMappingRepository.java
  src/main/java/com/gamegoo/gamegoo_v2/content/report/service/ReportFacadeService.java
  src/main/java/com/gamegoo/gamegoo_v2/content/report/service/ReportService.java
  src/main/java/com/gamegoo/gamegoo_v2/core/common/annotation/EachMax.java
  src/main/java/com/gamegoo/gamegoo_v2/core/common/annotation/EachMin.java
  src/main/java/com/gamegoo/gamegoo_v2/core/common/annotationValidator/EachMaxAnnotationValidator.java
  src/main/java/com/gamegoo/gamegoo_v2/core/common/annotationValidator/EachMinAnnotationValidator.java
  src/main/java/com/gamegoo/gamegoo_v2/core/event/SendReportEmailEvent.java
  src/main/java/com/gamegoo/gamegoo_v2/core/event/listener/EmailEventListener.java
  src/main/java/com/gamegoo/gamegoo_v2/core/exception/ReportException.java
  src/main/java/com/gamegoo/gamegoo_v2/core/exception/common/ErrorCode.java
  src/main/java/com/gamegoo/gamegoo_v2/social/manner/controller/MannerController.java
  src/main/resources/application.yml
  src/main/resources/templates/new-report.html
  src/test/java/com/gamegoo/gamegoo_v2/controller/report/ReportControllerTest.java
  src/test/java/com/gamegoo/gamegoo_v2/integration/report/ReportFacadeServiceTest.java
  src/test/resources/application.yml
Labels: :sparkles: feature, ✅ test

#160 [Feat/159] 게시물 삭제 로직
  src/main/java/com/gamegoo/gamegoo_v2/content/board/controller/BoardController.java
  src/main/java/com/gamegoo/gamegoo_v2/content/board/domain/Board.java
  src/main/java/com/gamegoo/gamegoo_v2/content/board/service/BoardFacadeService.java
  src/main/java/com/gamegoo/gamegoo_v2/content/board/service/BoardService.java
Labels: :sparkles: feature

#166 [Fix/165] 신고 등록 시 관리자 메일 발송 버그 수정
  src/main/java/com/gamegoo/gamegoo_v2/account/email/service/EmailService.java
  src/main/java/com/gamegoo/gamegoo_v2/content/report/dto/request/ReportRequest.java
  src/main/java/com/gamegoo/gamegoo_v2/core/event/listener/EmailEventListener.java
  src/test/java/com/gamegoo/gamegoo_v2/controller/report/ReportControllerTest.java
Labels: :bug: bug

#167 [Feat/163] 매너 정보 및 매너 키워드 개수 조회 API 분리
  src/main/java/com/gamegoo/gamegoo_v2/social/manner/controller/MannerController.java
  src/main/java/com/gamegoo/gamegoo_v2/social/manner/dto/response/MannerKeywordListResponse.java
  src/main/java/com/gamegoo/gamegoo_v2/social/manner/dto/response/MannerResponse.java
  src/main/java/com/gamegoo/gamegoo_v2/social/manner/service/MannerFacadeService.java
  src/test/java/com/gamegoo/gamegoo_v2/controller/manner/MannerControllerTest.java
  src/test/java/com/gamegoo/gamegoo_v2/integration/manner/MannerFacadeServiceTest.java
Labels: :sparkles: feature, ✅ test

#168 [Feat/163] 매너 정보 및 키워드 조회 API 버그 수정
  src/main/java/com/gamegoo/gamegoo_v2/core/config/WebConfig.java
  src/main/java/com/gamegoo/gamegoo_v2/social/manner/repository/MannerRatingKeywordRepositoryCustomImpl.java
Labels: :bug: bug

#164 [Feat/154] Security 설정 및 Jwt @AuthMember 연동
  build.gradle
  src/main/java/com/gamegoo/gamegoo_v2/account/auth/annotation/resolver/AuthMemberArgumentResolver.java
  src/main/java/com/gamegoo/gamegoo_v2/account/auth/domain/Role.java
  src/main/java/com/gamegoo/gamegoo_v2/account/auth/jwt/JwtInterceptor.java
  src/main/java/com/gamegoo/gamegoo_v2/account/auth/security/CustomAccessDeniedHandler.java
  src/main/java/com/gamegoo/gamegoo_v2/account/auth/security/CustomUserDetails.java
  src/main/java/com/gamegoo/gamegoo_v2/account/auth/security/CustomUserDetailsService.java
  src/main/java/com/gamegoo/gamegoo_v2/account/auth/security/EntryPointUnauthorizedHandler.java
  src/main/java/com/gamegoo/gamegoo_v2/account/auth/security/JwtAuthFilter.java
  src/main/java/com/gamegoo/gamegoo_v2/account/auth/security/JwtAuthenticationExceptionHandler.java
  src/main/java/com/gamegoo/gamegoo_v2/account/auth/security/SecurityUtil.java
  src/main/java/com/gamegoo/gamegoo_v2/account/member/domain/LoginType.java
  src/main/java/com/gamegoo/gamegoo_v2/core/config/SecurityConfig.java
  src/main/java/com/gamegoo/gamegoo_v2/core/config/WebConfig.java
  src/main/java/com/gamegoo/gamegoo_v2/core/exception/AuthException.java
Labels: :sparkles: feature

#171 [Test/169] 시큐리티 도입으로 인한 테스트코드 수정 및 SecurityConfig 리팩토링
  build.gradle
  src/main/java/com/gamegoo/gamegoo_v2/account/auth/annotation/resolver/AuthMemberArgumentResolver.java
  src/main/java/com/gamegoo/gamegoo_v2/account/auth/security/JwtAuthFilter.java
  src/main/java/com/gamegoo/gamegoo_v2/core/config/SecurityConfig.java
  src/main/java/com/gamegoo/gamegoo_v2/core/config/SecurityJwtProperties.java
  src/main/resources/application.yml
  src/main/resources/excluded-paths.yml
  src/test/java/com/gamegoo/gamegoo_v2/controller/ControllerTestSupport.java
  src/test/java/com/gamegoo/gamegoo_v2/controller/WithCustomMockAdmin.java
  src/test/java/com/gamegoo/gamegoo_v2/controller/WithCustomMockAdminSecurityContextFactory.java
  src/test/java/com/gamegoo/gamegoo_v2/controller/WithCustomMockMember.java
  src/test/java/com/gamegoo/gamegoo_v2/controller/WithCustomMockMemberSecurityContextFactory.java
  src/test/java/com/gamegoo/gamegoo_v2/controller/block/BlockControllerTest.java
  src/test/java/com/gamegoo/gamegoo_v2/controller/chat/ChatControllerTest.java
  src/test/java/com/gamegoo/gamegoo_v2/controller/friend/FriendControllerTest.java
  src/test/java/com/gamegoo/gamegoo_v2/controller/internal/InternalControllerTest.java
  src/test/java/com/gamegoo/gamegoo_v2/controller/manner/MannerControllerTest.java
  src/test/java/com/gamegoo/gamegoo_v2/controller/notification/NotificationControllerTest.java
  src/test/java/com/gamegoo/gamegoo_v2/controller/report/ReportControllerTest.java
Labels: :recycle: refactor, ✅ test

#173 [Cicd/172] 서버 timezone KST로 설정
  Dockerfile
Labels: :construction_worker: cicd

#174 [Cicd/172] github_actions.yml 수정
  .github/workflows/github_actions.yml
Labels: :construction_worker: cicd

#170 [Feat/161] 내가 작성한 게시판 글 목록 조회 API
  src/main/java/com/gamegoo/gamegoo_v2/content/board/controller/BoardController.java
  src/main/java/com/gamegoo/gamegoo_v2/content/board/dto/response/MyBoardListResponse.java
  src/main/java/com/gamegoo/gamegoo_v2/content/board/dto/response/MyBoardResponse.java
  src/main/java/com/gamegoo/gamegoo_v2/content/board/repository/BoardRepository.java
  src/main/java/com/gamegoo/gamegoo_v2/content/board/service/BoardFacadeService.java
  src/main/java/com/gamegoo/gamegoo_v2/content/board/service/BoardService.java
Labels: :sparkles: feature

#177 [Feat/175] API 요청 LoggingFilter 구현
  src/main/java/com/gamegoo/gamegoo_v2/account/auth/annotation/resolver/AuthMemberArgumentResolver.java
  src/main/java/com/gamegoo/gamegoo_v2/account/auth/security/JwtAuthenticationExceptionHandler.java
  src/main/java/com/gamegoo/gamegoo_v2/account/auth/security/SecurityUtil.java
  src/main/java/com/gamegoo/gamegoo_v2/core/config/SecurityConfig.java
  src/main/java/com/gamegoo/gamegoo_v2/core/log/LogUtil.java
  src/main/java/com/gamegoo/gamegoo_v2/core/log/LoggingFilter.java
  src/test/java/com/gamegoo/gamegoo_v2/controller/ControllerTestSupport.java
Labels: :sparkles: feature

#179 [Feat/176] 포지션 자료형 int -> ENUM 변경
  src/main/java/com/gamegoo/gamegoo_v2/account/member/domain/Member.java
  src/main/java/com/gamegoo/gamegoo_v2/account/member/domain/Position.java
  src/main/java/com/gamegoo/gamegoo_v2/account/member/dto/request/PositionRequest.java
  src/main/java/com/gamegoo/gamegoo_v2/account/member/dto/response/MyProfileResponse.java
  src/main/java/com/gamegoo/gamegoo_v2/account/member/dto/response/OtherProfileResponse.java
  src/main/java/com/gamegoo/gamegoo_v2/account/member/service/MemberService.java
  src/test/java/com/gamegoo/gamegoo_v2/integration/member/MemberServiceFacadeTest.java
Labels: ✅ test

#180 [Feat/178] 로그 파일 일별 저장 설정
  .github/workflows/github_actions.yml
  src/main/resources/logback-spring.xml
Labels: :sparkles: feature

#183 [Feat/181] 매칭 DB 설계 및 Mike ENUM 추가
  src/main/java/com/gamegoo/gamegoo_v2/account/member/controller/MemberController.java
  src/main/java/com/gamegoo/gamegoo_v2/account/member/domain/Member.java
  src/main/java/com/gamegoo/gamegoo_v2/account/member/domain/Mike.java
  src/main/java/com/gamegoo/gamegoo_v2/account/member/dto/request/IsMikeRequest.java
  src/main/java/com/gamegoo/gamegoo_v2/account/member/dto/response/MyProfileResponse.java
  src/main/java/com/gamegoo/gamegoo_v2/account/member/dto/response/OtherProfileResponse.java
  src/main/java/com/gamegoo/gamegoo_v2/account/member/service/MemberFacadeService.java
  src/main/java/com/gamegoo/gamegoo_v2/account/member/service/MemberService.java
  src/main/java/com/gamegoo/gamegoo_v2/matching/domain/GameMode.java
  src/main/java/com/gamegoo/gamegoo_v2/matching/domain/MatchingRecord.java
  src/main/java/com/gamegoo/gamegoo_v2/matching/domain/MatchingStatus.java
  src/test/java/com/gamegoo/gamegoo_v2/integration/member/MemberServiceFacadeTest.java
Labels: :sparkles: feature

#187 [Feat/185] ENUM으로 자료형 통일 및 일부 테스트 코드 수정
  src/main/java/com/gamegoo/gamegoo_v2/content/board/controller/BoardController.java
  src/main/java/com/gamegoo/gamegoo_v2/content/board/domain/Board.java
  src/main/java/com/gamegoo/gamegoo_v2/content/board/dto/request/BoardInsertRequest.java
  src/main/java/com/gamegoo/gamegoo_v2/content/board/dto/request/BoardUpdateRequest.java
  src/main/java/com/gamegoo/gamegoo_v2/content/board/dto/response/BoardByIdResponse.java
  src/main/java/com/gamegoo/gamegoo_v2/content/board/dto/response/BoardByIdResponseForMember.java
  src/main/java/com/gamegoo/gamegoo_v2/content/board/dto/response/BoardInsertResponse.java
  src/main/java/com/gamegoo/gamegoo_v2/content/board/dto/response/BoardListResponse.java
  src/main/java/com/gamegoo/gamegoo_v2/content/board/dto/response/BoardUpdateResponse.java
  src/main/java/com/gamegoo/gamegoo_v2/content/board/repository/BoardRepository.java
  src/main/java/com/gamegoo/gamegoo_v2/content/board/service/BoardFacadeService.java
  src/main/java/com/gamegoo/gamegoo_v2/content/board/service/BoardService.java
  src/test/java/com/gamegoo/gamegoo_v2/integration/chat/ChatFacadeServiceTest.java
  src/test/java/com/gamegoo/gamegoo_v2/integration/report/ReportFacadeServiceTest.java
  src/test/java/com/gamegoo/gamegoo_v2/service/chat/ChatCommandServiceTest.java
Labels: :sparkles: feature

#188 [Feat/184] 게시물 욕설 필터링 로직 구현
  src/main/java/com/gamegoo/gamegoo_v2/content/board/service/BoardFacadeService.java
  src/main/java/com/gamegoo/gamegoo_v2/content/board/service/ProfanityCheckService.java
  src/main/java/com/gamegoo/gamegoo_v2/core/exception/common/ErrorCode.java
  src/main/resources/bad-words.txt
  src/test/java/com/gamegoo/gamegoo_v2/service/board/ProfanityCheckServiceTest.java
Labels: :sparkles: feature
